name: HomeLife
favicon: null
layout_spectrum: 0.96734
typography_spectrum: 0.07447
title: Sad American Home Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a79d9c'
    - '#f7ede4'
    - '#726867'
    - '#33282e'
    - '#190c13'
  brandStrength: 0.75
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: stars
    item: null
    url: null
